- id: f32f7fc67467278b
  type: global-config
  env:
    - name: MQTT_USER
      value: librecoach
      type: str
    - name: MQTT_PASS
      value: One23four
      type: str
  modules: {}
  normalizedLabel: global-config
